language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - pip install unittest2
  - pip install pep8

before_script: python setup.py pep8
script: python setup.py test

notifications:
  email:
    - rahul.rrixe@gmail.com
